name: Generate GitHub Trophies

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Trophies
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=vishnurj06&theme=flat&column=6&row=3&no-frame=true'
          path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trophy.svg

          git diff --cached --quiet || git commit -m "Update GitHub trophies"

          git push
